FROM bd2kbdds/base_image
 
COPY gatk2/ /usr/local/gatk2_variant_annotator/gatk2/GenomeAnalysisTK-2.8-1-g932cd3a/
COPY samtools/ /usr/local/gatk2_variant_annotator/samtools/1.2/
 
ENV PATH /usr/local/gatk2_variant_annotator/gatk2/GenomeAnalysisTK-2.8-1-g932cd3a:"
ENV PATH "$/usr/local/gatk2_variant_annotator/gatk2/GenomeAnalysisTK-2.8-1-g932cd3a:$PATH"
 
ENV PATH /usr/local/gatk2_variant_annotator/samtools/1.2/bin:$PATH"
