FROM bd2kbdds/base_image
 
COPY vcftools/ /usr/local/vcftools_annotate/vcftools/vcftools_0.1.11/
 
ENV PATH /usr/local/vcftools_annotate/vcftools/vcftools_0.1.11/bin/:$PATH"
ENV PATH "$/usr/local/vcftools_annotate/vcftools/vcftools_0.1.11:$PATH"
