FROM bd2kbdds/base_image
 
COPY samtools/ /usr/local/defuse/samtools/1.2/
COPY bowtie/ /usr/local/defuse/bowtie/1.1.2/
 
ENV PATH /usr/local/defuse/samtools/1.2/bin:$PATH"
 
ENV PATH /usr/local/defuse/bowtie/1.1.2:$PATH"
