FROM bd2kbdds/base_image
 
COPY rsem/ /usr/local/rsem_calculate_expression/rsem/1.2.28/
ENV PATH "$/usr/local/rsem_calculate_expression/rsem/1.2.28:$PATH"
 
ENV PATH /usr/local/rsem_calculate_expression/rsem/1.2.28:"
