FROM bd2kbdds/base_image
 
COPY gatk/ /usr/local/gatk2_depth_of_coverage/gatk/1.0.5974/
COPY samtools/ /usr/local/gatk2_depth_of_coverage/samtools/1.2/
 
ENV PATH /usr/local/gatk2_depth_of_coverage/gatk/1.0.5974/bin:$PATH"
 
ENV PATH /usr/local/gatk2_depth_of_coverage/samtools/1.2/bin:$PATH"
