FROM bd2kbdds/base_image
 
COPY trimmomatic/ /usr/local/trimmomatic/trimmomatic/Trimmomatic-0.32/
 
ENV PATH /usr/local/trimmomatic/trimmomatic/Trimmomatic-0.32:$PATH"
ENV PATH "$/usr/local/trimmomatic/trimmomatic/Trimmomatic-0.32:$PATH"
ENV PATH "$/usr/local/trimmomatic/trimmomatic/Trimmomatic-0.32:$PATH"
