FROM bd2kbdds/base_image
 
COPY gatk/ /usr/local/gatk_count_covariates/gatk/1.0.5974/
COPY samtools/ /usr/local/gatk_count_covariates/samtools/1.2/
 
ENV PATH /usr/local/gatk_count_covariates/gatk/1.0.5974/bin:$PATH"
 
ENV PATH /usr/local/gatk_count_covariates/samtools/1.2/bin:$PATH"
