FROM bd2kbdds/base_image
 
COPY R/ /usr/local/shRNAseq/R/3.2.2/
ENV PATH "$/usr/local/shRNAseq/R/3.2.2:$PATH"
 
ENV PATH /usr/local/shRNAseq/R/3.2.2/bin/bin:$PATH"
ENV PATH "$/usr/local/shRNAseq/R/3.2.2:$PATH"
