FROM bd2kbdds/base_image
 
COPY fastx_toolkit/ /usr/local/cshl_fastx_nucleotides_distribution/fastx_toolkit/0.0.13/
 
ENV PATH /usr/local/cshl_fastx_nucleotides_distribution/fastx_toolkit/0.0.13/bin:$PATH"
